### ISSUE TITLE
Everything in my clipboard suddenly disappeared

### ISSUE THREAD

**Issue by AGPVEN** [przybylski/permanent-clipboard#2]
Hi, I had maybe 20 to 25 items in my clipboard and all of it disappeared as of this morning.

1) Is there a way to recover it all?
2) Is there a way to back it all up in the future?

Thanks.

**Comment by AGPVEN** [comment]
Hi, I just discovered that all my clipboard items are still available through the context menu. WHAT A RELIEF!!! So I suspect that my browser needs a refresh or something. Still....is there a way to back up these things?

**Comment by przybylski** [comment]
Hi @AGPVEN thanks for your feedback. I'm glad your data is safe.
So far there is no way to backup your entries, but if you use synchronized storage then your data is stored on google servers, so it won't magically disappear, unless you delete it.

Recently I have moved this project aside since there is not such a great interest in it. It's been out for almost 3 years and it has less than 10k users, so I don't plan to put too much focus on it. But in the future I do plan to add import/export feature there.
